name: Keploy API Testing CI/CD

on:
  push:
    branches:
      - main

jobs:
  keploy-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Download Keploy CLI
      run: |
        curl -sSfL https://get.keploy.io | sh
        sudo mv keploy /usr/local/bin/
        keploy version

    - name: Run API server in background
      run: |
        source venv/bin/activate
        nohup python app.py > server.log 2>&1 &
        sleep 5

    - name: Run Keploy Test
      run: |
        keploy test --path keploy/test-set-2
