name: Keploy API Testing CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  keploy-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - "27017:27017"
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand(\"ping\").ok'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # 🔁 Change if your version is different

      - name: Install application dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask pymongo Flask-Cors flasgger

      - name: Install Keploy CLI
        run: |
          curl --silent -O -L https://keploy.io/install.sh && sudo bash install.sh

      - name: Prepare eBPF Hooks
        run: |
          sudo mkdir -p /sys/kernel/debug
          sudo mkdir -p /sys/kernel/tracing
          sudo mount -t debugfs nodev /sys/kernel/debug || true
          sudo mount -t tracefs nodev /sys/kernel/tracing || true

      - name: Run Keploy Test Suite with API Key and Custom App Info
        run: |
          export KEPLOY_API_KEY=/v3KbR7wwlEy8LXMKA==
          sudo -E keploy test-suite \
            --app=a271740b-cc4c-4568-a3ab-ca274c9c9608 \
            --base-path https://e914-47-31-113-124.ngrok-free.app/clients \
            --cloud
        env:
          FLASK_APP: app.py
